### ISSUE TITLE
400 or 422?

### ISSUE THREAD

**Issue by JanaVPetrova** [mattt/sinatra-param#44]
Hello!

The documentation says that the app will return 400 if params are not valid. But status code 400 is only for syntax errors in the requests.
If syntax is OK and params are not valid because of the business logic (for example, email should match example@mail.com and it doesn't), the app should return status code 422 Unprocessable Entity.
(http://www.restapitutorial.com/httpstatuscodes.html)

So, is there any difference between these two cases?

**Comment by mattt** [comment]
This is a great question, @JanaVPetrova.

This tension between HTTP codes 400 and 422 has been a source of consternation for many protocol geeks (myself included) for quite a while. 422 was introduced in [RFC 4918](https://tools.ietf.org/html/rfc4918#section-11.2) as part of the WebDAV extension to HTTP. Because it is perceived as an extension, rather than a core part of HTTP semantics, it could be deemed inappropriate for use in non-WebDAV applications. 

One of the changes in the [HTTPbis](http://tools.ietf.org/html/draft-ietf-httpbis-p2-semantics-26#section-6.5.1) spec is that 400 "indicates that the server cannot or will not process the request due to something which is perceived to be a client error". Although it used to only be used to specify a syntax error, it is now being expanded to include semantic errors as well, much like 422, but for all HTTP.

So although 400 may not be a perfect fit now, it will be in the future. As such, I'm fine with its current usage in this library.

**Comment by JanaVPetrova** [comment]
Thank you for the answer!
