### ISSUE TITLE
README request - include example using URI.regexp

### ISSUE THREAD

**Issue by hangtwenty** [mattt/sinatra-param#73]
Since it seems like something that might come up here and there, maybe it would be good to show a `format` example with [`URI.regexp`](http://ruby-doc.org/stdlib-2.3.1/libdoc/uri/rdoc/URI.html#method-c-regexp). It seems simple, but to a Ruby newb like me (coming from Python), this was a little _A-ha! Nice!_ moment... I mean, it's not _necessary_ but it is a common use case anyway (pretty common for someone to put in a URL into a form, linking accounts etc.) ... yeah, why not show an easy case.

Totally understand if this seems gratuitous just figured I'd suggest it and throw up a PR.

**Comment by hangtwenty** [comment]
Seriously no worries if this doesn't make sense, just figured I'd suggest & PR

**Comment by mattt** [comment]
This is indeed a cool use of existing functionality, and one that I hadn't considered previously. Thanks for sharing, @hangtwenty.

As for whether this should go in the README, that's hard to say. I'm leaning towards not for the following reasons:

- It requires an extra `require`
- It doesn't seem to fit with the current example of a search endpoint
- Referrers are typically sent as an HTTP header, rather than in the URL query
- Matching `URI.regexp` doesn't actually imply that a valid URL; most HTTP implementations limit the length of a URL to 2038 characters, however the following statement still returns `true`: `URI.regexp.match? "http://a.com/" + ("a" * 5000)`

All of that said, I think the documentation could do a better job of explaining how one might initialize domain or model objects from parameters, and what the relationship is there. I'm looking into how this could be improved in a future version.
